# -*- coding: utf-8 -*-
"""Implementasi_Criptografi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19lFWzBeaUtKCaqxU6wYC_obevQiz9pDr

# IMPLEMENTASI ENCODING DAN DECODING DENGAN PYTHON

* Install Cryptografi dalam Python
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install cryptography

import pandas as pd
from cryptography.fernet import Fernet

! wget https://raw.githubusercontent.com/DodikSukma/Data-Science-Klasifikasi-01/main/Status%20Nutrition%20Dataset.csv

"""# SEBELUM ENCODING"""

se = pd.read_csv('Status Nutrition Dataset.csv')
se.head(15)

"""# PROSES ENCODING MENGGUNAKAN METODE FERNET"""

# mendelkarasikan kunci fernet
key = Fernet.generate_key()
 
# Mendeklarasikan Huruf Acak sebagai bahan encoding
with open('filekey.key', 'wb') as filekey:
   filekey.write(key)

# Melihat Deklarasikan Huruf Acuan 
key

with open('filekey.key', 'rb') as filekey:
    key = filekey.read()
fernet = Fernet(key)
 
# Membuka File yang akan di enkripsi
with open('Status Nutrition Dataset.csv', 'rb') as file:
    original = file.read()
     
# Melakukan Enkripsi
encrypted = fernet.encrypt(original)
 
# Memulai proses enkripsi
with open('Status Nutrition Dataset Encripsi.csv', 'wb') as encrypted_file:
    encrypted_file.write(encrypted)

enkripsi_dataset = pd.read_csv('Status Nutrition Dataset Encripsi.csv')
enkripsi_dataset

"""* Mengembalikan  Dataset ke Bentuk Semula"""

# Mendeklarasikan Kunci Kembali
fernet = Fernet(key)
 
# Membuka Dataset yang sudah di enkripsi
with open('Status Nutrition Dataset Encripsi.csv', 'rb') as enc_file:
    encrypted = enc_file.read()
 
# Melakukan Dekripsi Dataset
decrypted = fernet.decrypt(encrypted)
 
# melakukan dekirpsi dataset
with open('Dataset Status Gizi Dekripsi.csv', 'wb') as dec_file:
    dec_file.write(decrypted)

dekripsi_dataset = pd.read_csv('Dataset Status Gizi Dekripsi.csv')
dekripsi_dataset